# Зямзина Анастасия Сергеевна 3530903/70302 Задание 3.2#
## Для 2.1: 8 вариант ##
## Для 3.1 и 3.2: 7 вариант ##

In [1]:
""" Для заданного пользователя (совпадает с вашим номером в таблице) 
рассчитать оценки для всех фильмов, которые он не оценил """
import numpy as np
import pandas as pd
import matplotlib
import math as m

#Параметры для расчета метрики сходства
my_user = 8
variant = my_user-1
kNN = 4

data = pd.read_csv('data.csv')
data = data.drop(data.columns[0],axis = 1)
data = data.replace({-1:None})
sred_v = round(data.iloc[[variant]].mean(axis = 1),3)
print("Средняя оценка", sred_v)


""" Составим метрику сходства для пользователей
    Для расчета метрики сходства был создан пустой масив Mat
    sum_p - числитель в выше рпедставленной формуле (сумма произведений оценок пользователей u, v)
    sum_u - левая часть произведения знаменателя - сумма квадратов оценок пользователя u
    sum_v - правая часть произведения знаменателя - сумма квадратов оценок пользователя v
"""
Mat = np.zeros((40,40)) 
data_to_eval = data.replace({None:0}).copy()
for user1 in range(40):
    for user2 in range(40):
        if(user1 != user2):
            sum_p = 0
            sum_u = 0
            sum_v = 0
            A = data_to_eval.iloc[lambda df: [user1,user2]].copy()
            for film in range(len(A.columns)):
                f_i = A[A.columns[film]].copy()
                if(int(f_i[user1]) != 0 and int(f_i[user2]) != 0):
                    sum_p = sum_p + int(f_i[user1]) * int(f_i[user2])
                    sum_u = sum_u + int(f_i[user1])**2 
                    sum_v = sum_v + int(f_i[user2])**2 
            sum_denumerator = m.sqrt(sum_u) * m.sqrt(sum_v)
            Mat[user1,user2] = round(sum_p / sum_denumerator,3)
print("Матрица сходства:\n",Mat)
print("Moй кортеж требуемых значений:\n", Mat[variant])
sim = Mat[variant]

"""Найдем индексы макисмальных значений (что и будет означать максимально похожих пользователей)
    Функция расставит в порядке возрастания, а я отслайсирую последние 4"""
ind = np.argpartition(Mat[variant], -kNN)[-kNN:]
print("Индексы максимально похожих", kNN,"пользователей:",ind) 

"""Фильмы, у которых нет оценок"""
data = pd.read_csv('data.csv')
data = data.drop(data.columns[0],axis = 1)
data_for_variant = data.replace({-1:0}).copy()
data_for_variant = data_for_variant.iloc[variant]
films_to_evaluate = dict()
sum_m = dict()
for i in range(30):
    if data_for_variant.iloc[i] == 0:
        films_to_evaluate[i] = 0 
        sum_m[i] = 0
print("Фильмы без оценок:",films_to_evaluate)

"""Для расчета оценки использовалась представленная выше формула.
   sum_m - сумма метрик сходства пользователей по каждрму фильму
   films_to_evaluate - словарь с индексами фильмов для оценки (не оценнеых прежде требуемым пользователем)
"""
sredv = sred_v[variant] 
data_to_get_sred = data.replace({-1:None}).copy()
for user1 in ind:
    dU = data_to_get_sred.iloc[[user1]] 
    sredu = round(dU.mean(axis = 1),3)
    sredu = sredu[user1] 
    for film in films_to_evaluate.keys():
        if(data.iloc[user1][film] != -1):
            sum_m[film] += sim[user1]
            films_to_evaluate[film] += sim[user1] * (data.iloc[user1][film] - sredu)
for i in films_to_evaluate.keys():
    films_to_evaluate[i] = round(sredv + round(films_to_evaluate[i] / abs(sum_m[i]),3),3)
print("Новые оценки для варианта:", films_to_evaluate)

names_for_films = data.iloc[variant].keys()
answer_21 = dict()
for i in films_to_evaluate.keys():
    answer_21[names_for_films[i]] = films_to_evaluate[i]
print("2.1 1 часть ответ: ",answer_21)

Средняя оценка 7    3.292
dtype: float64
Матрица сходства:
 [[0.    0.79  0.741 ... 0.891 0.745 0.83 ]
 [0.79  0.    0.742 ... 0.852 0.766 0.835]
 [0.741 0.742 0.    ... 0.812 0.806 0.729]
 ...
 [0.891 0.852 0.812 ... 0.    0.809 0.886]
 [0.745 0.766 0.806 ... 0.809 0.    0.799]
 [0.83  0.835 0.729 ... 0.886 0.799 0.   ]]
Moй кортеж требуемых значений:
 [0.812 0.896 0.756 0.837 0.8   0.907 0.849 0.    0.835 0.754 0.802 0.858
 0.747 0.835 0.857 0.875 0.81  0.823 0.887 0.88  0.814 0.742 0.785 0.838
 0.783 0.807 0.848 0.93  0.817 0.857 0.835 0.815 0.796 0.871 0.773 0.816
 0.832 0.774 0.814 0.799]
Индексы максимально похожих 4 пользователей: [18  1  5 27]
Фильмы без оценок: {0: 0, 10: 0, 12: 0, 17: 0, 20: 0, 27: 0}
Новые оценки для варианта: {0: 3.425, 10: 4.1, 12: 5.169, 17: 3.854, 20: 2.882, 27: 3.932}
2.1 1 часть ответ:  {' Movie 1': 3.425, ' Movie 11': 4.1, ' Movie 13': 5.169, ' Movie 18': 3.854, ' Movie 21': 2.882, ' Movie 28': 3.932}


## 2 часть этого задания

In [2]:
import numpy as np
import pandas as pd
import matplotlib
import math as m
variant = 7
kNN = 4
days = [' Sat',' Sun']
place = ['h']
data = pd.read_csv('data.csv')
data = data.drop(data.columns[0],axis = 1)
contday = pd.read_csv("context_day.csv")
contday = contday.drop(contday.columns[0],axis = 1)
contpl = pd.read_csv("context_place.csv")
contpl = contpl.drop(contpl.columns[0],axis = 1)

close_ind = np.argpartition(Mat[variant], -kNN)[-kNN:]

duser = data.iloc[variant].copy()
duser = duser.transpose()
for i in range(30):
    if duser.iloc[i] != -1:
        duser.iloc[i] = np.NaN
answer = duser.dropna()
no_rate = answer.keys()

film_vac_ev = answer.copy()
data_to_get_sred = data.replace({-1:None}).copy()
films_to_eval_with_context = {}

for film in no_rate:
    sumt = 0
    sumb = 0
    for user in close_ind:
        dU = data_to_get_sred.iloc[[user]] 
        sredu = round(dU.mean(axis = 1),3)
        rate = data.loc[user, film]
        if rate != -1:
            if contday.loc[user, film] in days:
                sumb += sim[user]
                sumt += sim[user] * (data.loc[user, film] - sredu[user])
        films_to_eval_with_context[film] = round(sumt/sumb,3) if sumb !=0 else 0


for film in no_rate:
    sumt = 0
    sumb = 0
    for user in close_ind:
        dU = data_to_get_sred.iloc[[user]] 
        sredu = round(dU.mean(axis = 1),3)
        rate = data.loc[user, film]
        if rate != -1 and contpl.loc[user, film] == ' h':
            sumb += sim[user]
            sumt += sim[user] * (data.loc[user, film] - sredu[user])
            films_to_eval_with_context[film] += sumt/sumb if sumb !=0 else 0
            films_to_eval_with_context[film] = round(films_to_eval_with_context[film],3)


data_to_get_sred = data.replace({-1:None}).copy()
sred_v = round(data_to_get_sred.iloc[[variant]].mean(axis = 1),3)
sredv = sred_v[variant]


for film in no_rate:
    films_to_eval_with_context[film] = round(films_to_eval_with_context[film] + sredv,3)

c = 0
contday = contday.replace({' -1':np.NaN})
film_vac_ev = {}
for film in no_rate:
    c = contday[film].value_counts() 
    sSat = c[[' Sun']]
    sSun = c[[' Sat']]
    c = c.dropna()
    views = c.sum()
    """ основная формула расчёта: отношение суммы просмотров на выходных к общему количеству просмотров ( вычитается из 1, т.к. чем
    выше просмотры => тем меньше дробь, а я в дальнейшем планирую суммировать оценки => мне нужен не меньший, а больший рейтинг)"""
    sumVac = 1 - round((sSat[0] + sSun[0]) / views,3)
    film_vac_ev[film] = sumVac 
    
c = 0
film_home_ev = {}
contpl = contpl.replace({' -1':np.NaN})
for film in no_rate:
    c = contpl[film].value_counts() 
    sh = c[[' h']]
    c = c.dropna()
    views = c.sum()
    sumh = 1 - round(sh[0] / views,3)
    film_home_ev[film] = sumh
koef = {}
for film in no_rate:
    koef[film] = round(film_home_ev[film] * film_vac_ev[film],3)

eval_cont = {}
for film in no_rate:
    eval_cont[film] = round(films_to_eval_with_context[film] * koef[film],3)


max_key = max(eval_cont, key=lambda k: eval_cont[k])
print("Рекомендуменый фильм:",max_key, "\nЕго оценка:", eval_cont[max_key])

Рекомендуменый фильм:  Movie 28 
Его оценка: 3.399


## Выведение результатов json

In [3]:
import json
answer = dict()

answer = {'user':8, 
          1: answer_21, 
          2: { max_key : eval_cont[max_key]}
         }
import json
res = json.dumps(answer, indent=4) 
result = json.loads(res)
with open('zyamzina_results.json', 'w') as fl:
    fl.write(json.dumps(result, indent=4) )
answer

{'user': 8,
 1: {' Movie 1': 3.425,
  ' Movie 11': 4.1,
  ' Movie 13': 5.169,
  ' Movie 18': 3.854,
  ' Movie 21': 2.882,
  ' Movie 28': 3.932},
 2: {' Movie 28': 3.399}}

# Задание 3.2

## список фильмов режиссера рекомендованного фильма

In [4]:
"""Поиск названия рекомендованного фильма"""

moviename = pd.read_csv("movie_names.csv", header=None,delimiter=',')
for i in range(len(moviename)):
    if(moviename[0][i] == max_key.lstrip()):
        movie_name = moviename[1][i].lstrip()
movie_name

'Saving Private Ryan'

In [5]:
from SPARQLWrapper import SPARQLWrapper, JSON
import pandas as pd
import requests
API_ENDPOINT = "https://www.wikidata.org/w/api.php"
params = {
    'action' : 'wbsearchentities',
    'format' : 'json',
    'language' : 'en',
    'search': movie_name
}
res = requests.get(API_ENDPOINT, params = params)
res.json()['search'][0]['description']
res.json()

{'searchinfo': {'search': 'Saving Private Ryan'},
 'search': [{'id': 'Q165817',
   'title': 'Q165817',
   'pageid': 166417,
   'repository': 'wikidata',
   'url': '//www.wikidata.org/wiki/Q165817',
   'concepturi': 'http://www.wikidata.org/entity/Q165817',
   'label': 'Saving Private Ryan',
   'description': '1998 American epic war film directed by Steven Spielberg',
   'match': {'type': 'label',
    'language': 'en',
    'text': 'Saving Private Ryan'}},
  {'id': 'Q3945916',
   'title': 'Q3945916',
   'pageid': 3762858,
   'repository': 'wikidata',
   'url': '//www.wikidata.org/wiki/Q3945916',
   'concepturi': 'http://www.wikidata.org/entity/Q3945916',
   'label': 'Saving Private Ryan',
   'description': 'Soundtrack by John Williams',
   'match': {'type': 'label',
    'language': 'en',
    'text': 'Saving Private Ryan'}},
  {'id': 'Q40537196',
   'title': 'Q40537196',
   'pageid': 41875688,
   'repository': 'wikidata',
   'url': '//www.wikidata.org/wiki/Q40537196',
   'concepturi': 'ht

In [6]:
 filmcode=res.json()['search'][0]['id']

In [7]:
sparql = SPARQLWrapper("https://query.wikidata.org/sparql")

sparql_query = """

SELECT ?filmLabels ?filmLabelsLabel
WHERE {
  BIND(wd:"""+filmcode+""" AS ?my_film)
  ?my_film wdt:P57 ?director.
  ?filmLabels wdt:P31 wd:Q11424.
  ?filmLabels wdt:P57 ?director.
  FILTER(?filmLabels != ?my_film).
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],ru". }
}
"""

sparql.setQuery(sparql_query)

sparql.setReturnFormat(JSON)
results = sparql.query().convert()


In [8]:
results_df = pd.json_normalize(results['results']['bindings'])
results_df[['filmLabels.value', 'filmLabelsLabel.value']].head(32)

filmLabels.value  \
0      http://www.wikidata.org/entity/Q11621   
1      http://www.wikidata.org/entity/Q32433   
2     http://www.wikidata.org/entity/Q152456   
3     http://www.wikidata.org/entity/Q167726   
4     http://www.wikidata.org/entity/Q174284   
5     http://www.wikidata.org/entity/Q179215   
6     http://www.wikidata.org/entity/Q182373   
7     http://www.wikidata.org/entity/Q185658   
8     http://www.wikidata.org/entity/Q189505   
9     http://www.wikidata.org/entity/Q200873   
10    http://www.wikidata.org/entity/Q202028   
11    http://www.wikidata.org/entity/Q207482   
12    http://www.wikidata.org/entity/Q208108   
13    http://www.wikidata.org/entity/Q218589   
14    http://www.wikidata.org/entity/Q221113   
15    http://www.wikidata.org/entity/Q223299   
16    http://www.wikidata.org/entity/Q244604   
17    http://www.wikidata.org/entity/Q271281   
18    http://www.wikidata.org/entity/Q318766   
19    http://www.wikidata.org/entity/Q320588   
20    http://www.wikidata.org/entity/Q432526   
21    http://www.wikidata.org/entity/Q449743   
22    http://www.wikidata.org/entity/Q472361   
23    http://www.wikidata.org/entity/Q483941   
24    http://www.wikidata.org/entity/Q591320   
25   http://www.wikidata.org/entity/Q1330737   
26   http://www.wikidata.org/entity/Q3057871   
27  http://www.wikidata.org/entity/Q11791805   
28  http://www.wikidata.org/entity/Q18067135   
29  http://www.wikidata.org/entity/Q18276472   
30  http://www.wikidata.org/entity/Q30203425   
31  http://www.wikidata.org/entity/Q63643994   

                              filmLabelsLabel.value  
0                                     Инопланетянин  
1                                          Линкольн  
2                                            Мюнхен  
3                              Парк юрского периода  
4      Индиана Джонс: В поисках утраченного ковчега  
5                       Индиана Джонс и храм судьбы  
6   Индиана Джонс и Королевство хрустального черепа  
7         Индиана Джонс и последний крестовый поход  
8                                           Челюсти  
9              Парк юрского периода: Затерянный мир  
10                                      Война миров  
11                    Тысяча девятьсот сорок первый  
12                        Поймай меня, если сможешь  
13                                      Боевой конь  
14                              Искусственный разум  
15                              Цветы лиловые полей  
16                                    Особое мнение  
17                                   Империя солнца  
18                                         Терминал  
19                 Близкие контакты третьей степени  
20                           Шугарлендский экспресс  
21                                           Всегда  
22                                          Амистад  
23                                  Список Шиндлера  
24                                          Q591320  
25                                  Сумеречная зона  
26                                         Q3057871  
27                                        Q11791805  
28                                   Шпионский мост  
29                                        Q18276472  
30                                  Секретное досье  
31                             Вестсайдская история